apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: patches/operator-resources.yaml
  target:
    kind: Deployment
- path: patches/datadog-annotations-operator.yaml
  target:
    kind: Deployment

bases:
- ../../crds
- ../../base
