apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pulumi-operator

commonLabels:
  app: pulumi-operator

images:
- name: pulumi/pulumi-kubernetes-operator
  newName: docker.io/pulumi/pulumi-kubernetes-operator

resources:
- operator.yaml
- role.yaml
- role_binding.yaml
- secret.yaml
- service_account.yaml

