apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pulumi-operator

commonLabels:
  app: pulumi-operator

patches:
- path: patches/operator-resources.yaml
  target:
    kind: Deployment

resources:
- operator.yaml
- role.yaml
- role_binding.yaml
- secret.yaml
- service_account.yaml

