---
apiVersion: v1
kind: Secret
metadata:
  name: pulumi-api-secret
  annotations:
    vault.security.banzaicloud.io/mutate-configmap: "true"
    vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
    vault.security.banzaicloud.io/vault-role: vault
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vaultInjectionChecksum: a3e4e76dbc7ec66e1a35946f363d65b74066b5624e28925e0bbe53630e7f10f3
  labels:
    vault-injection: enabled
type: Opaque
data:
  accessToken: dmF1bHQ6c2VjcmV0L2RhdGEvcHVsdW1pI2FjY2Vzc1Rva2Vu
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  annotations:
    vault.security.banzaicloud.io/mutate-configmap: "true"
    vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
    vault.security.banzaicloud.io/vault-role: vault
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vaultInjectionChecksum: a3e4e76dbc7ec66e1a35946f363d65b74066b5624e28925e0bbe53630e7f10f3
  labels:
    vault-injection: enabled
type: Opaque
data:
  aws_access_key_id: dmF1bHQ6c2VjcmV0L2RhdGEvdmVsZXJvL2F3cyNhd3NfYWNjZXNzX2tleV9pZA==
  aws_secret_access_key: dmF1bHQ6c2VjcmV0L2RhdGEvdmVsZXJvL2F3cyNhd3Nfc2VjcmV0X2FjY2Vzc19rZXk=
