apiVersion: v1
kind: Secret
metadata:
  annotations:
    vault.security.banzaicloud.io/mutate-configmap: "true"
    vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
    vault.security.banzaicloud.io/vault-role: vault
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
  labels:
    vault-injection: enabled
  name: pulumi-api-secret
type: Opaque
stringData:
  accessToken: "vault:secret/data/pulumi#accessToken"
