---
apiVersion: v1
kind: Secret
metadata:
  name: pulumi-api-secret
  annotations:
    vault.security.banzaicloud.io/mutate-configmap: "true"
    vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
    vault.security.banzaicloud.io/vault-role: vault
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vaultInjectionChecksum: 34d394690a39e69d8e1e66179a268eb4eead972c028b2b2cd772ed43d1bc46d7
  labels:
    vault-injection: enabled
type: Opaque
data:
  accessToken: dmF1bHQ6c2VjcmV0L2RhdGEvcHVsdW1pI2FjY2Vzc1Rva2Vu
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  annotations:
    vault.security.banzaicloud.io/mutate-configmap: "true"
    vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
    vault.security.banzaicloud.io/vault-role: vault
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vaultInjectionChecksum: 34d394690a39e69d8e1e66179a268eb4eead972c028b2b2cd772ed43d1bc46d7
  labels:
    vault-injection: enabled
type: Opaque
data:
  aws_access_key_id: dmF1bHQ6c2VjcmV0L2RhdGEvdmVsZXJvL2F3cyNhd3NfYWNjZXNzX2tleV9pZA==
  aws_secret_access_key: dmF1bHQ6c2VjcmV0L2RhdGEvdmVsZXJvL2F3cyNhd3Nfc2VjcmV0X2FjY2Vzc19rZXk=
---
apiVersion: v1
kind: Secret
metadata:
  name: datadog-api-key
  annotations:
    vault.security.banzaicloud.io/mutate-configmap: "true"
    vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
    vault.security.banzaicloud.io/vault-role: vault
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vaultInjectionChecksum: 34d394690a39e69d8e1e66179a268eb4eead972c028b2b2cd772ed43d1bc46d7
  labels:
    vault-injection: enabled
type: Opaque
data:
  api-key: dmF1bHQ6c2VjcmV0L2RhdGEvZGF0YWRvZyNhcGkta2V5
  app-key: dmF1bHQ6c2VjcmV0L2RhdGEvZGF0YWRvZyNhcHAta2V5

