apiVersion: v1
kind: Secret
metadata:
  annotations:
    vault.security.banzaicloud.io/mutate-configmap: "true"
    vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
    vault.security.banzaicloud.io/vault-role: vault
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vaultInjectionChecksum: 92afb8879e9450d06325a865255d57294e7370ce862fb86a58eb6b2b9de1eaf7
  labels:
    vault-injection: enabled
  name: pulumi-api-secret
type: Opaque
data:
  accessToken: dmF1bHQ6c2VjcmV0L2RhdGEvcHVsdW1pI2FjY2Vzc1Rva2Vu
