apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: buckets
spec:
  envRefs:
    DATADOG_APP_KEY:
      type: Secret
      secret:
        name: datadog-api-key
        key: app-key
    DATADOG_API_KEY:
      type: Secret
      secret:
        name: datadog-api-key
        key: api-key
    AWS_SECRET_ACCESS_KEY:
      type: Secret
      secret:
        name: aws-credentials
        key: aws_secret_access_key
    AWS_ACCESS_KEY_ID:
      type: Secret
      secret:
        name: aws-credentials
        key: aws_access_key_id
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        key: accessToken
  stack: youvegotmoxie/buckets/us-east-1
  projectRepo: https://github.com/Unreliable-Cloud/pulumi-aws-buckets
  branch: "refs/heads/master"
  destroyOnFinalize: true

